# Generated by Django 3.1.2 on 2020-11-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='clubattr',
            name='pos',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='nation',
            name='flag',
            field=models.CharField(blank=True, help_text='Location of svg image of nation flag.', max_length=20, null=True),
        ),
    ]
